### ISSUE TITLE
An error occurred using the smplx model

### ISSUE THREAD

**Issue by songjiahao-wq** [DavidBoja/SMPL-Anthropometry#26]
Traceback (most recent call last):
  File "E:\project2024\SMPLX\SMPL-Anthropometry\measure.py", line 494, in <module>
    measurer.measure(measurement_names)
  File "E:\project2024\SMPLX\SMPL-Anthropometry\measure.py", line 103, in measure
    value = self.measure_length(m_name)
  File "E:\project2024\SMPLX\SMPL-Anthropometry\measure.py", line 123, in measure_length
    measurement_landmarks_inds = self.length_definitions[measurement_name]
KeyError: 'arm length (shoulder to elbow)'

**Comment by DavidBoja** [comment]
You are right - at some point I added new measurements for the SMPL body and not SMPLX one, so the possible measurements were not properly defined. It's fixed now. Let me know if everything works. 

I am going to add these measurements that are defined for SMPL and not for SMPLX at some point but at least for now the code will not break.

**Comment by DavidBoja** [comment]
Closing due to inactivity - feel free to reopen if necessary.
